In [2]:
import pandas as pd
data=pd.read_csv('CO2.csv')
print(data)

       Make        Model   Vehicle Class  Engine Size(L)  Cylinders  \
0     ACURA          ILX         COMPACT             2.0          4   
1     ACURA          ILX         COMPACT             2.4          4   
2     ACURA   ILX HYBRID         COMPACT             1.5          4   
3     ACURA      MDX 4WD     SUV - SMALL             3.5          6   
4     ACURA      RDX AWD     SUV - SMALL             3.5          6   
...     ...          ...             ...             ...        ...   
7380  VOLVO  XC40 T5 AWD     SUV - SMALL             2.0          4   
7381  VOLVO  XC60 T5 AWD     SUV - SMALL             2.0          4   
7382  VOLVO  XC60 T6 AWD     SUV - SMALL             2.0          4   
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD             2.0          4   
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD             2.0          4   

     Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
0             AS5         Z                               9.9   
1              M6

In [3]:
data.transpose()

0        1           2            3     \
Make                                ACURA    ACURA       ACURA        ACURA   
Model                                 ILX      ILX  ILX HYBRID      MDX 4WD   
Vehicle Class                     COMPACT  COMPACT     COMPACT  SUV - SMALL   
Engine Size(L)                        2.0      2.4         1.5          3.5   
Cylinders                               4        4           4            6   
Transmission                          AS5       M6         AV7          AS6   
Fuel Type                               Z        Z           Z            Z   
Fuel Consumption City (L/100 km)      9.9     11.2         6.0         12.7   
Fuel Consumption Hwy (L/100 km)       6.7      7.7         5.8          9.1   
Fuel Consumption Comb (L/100 km)      8.5      9.6         5.9         11.1   
Fuel Consumption Comb (mpg)            33       29          48           25   
CO2 Emissions(g/km)                   196      221         136          255   

                                         4         5         6         7     \
Make                                    ACURA     ACURA     ACURA     ACURA   
Model                                 RDX AWD       RLX        TL    TL AWD   
Vehicle Class                     SUV - SMALL  MID-SIZE  MID-SIZE  MID-SIZE   
Engine Size(L)                            3.5       3.5       3.5       3.7   
Cylinders                                   6         6         6         6   
Transmission                              AS6       AS6       AS6       AS6   
Fuel Type                                   Z         Z         Z         Z   
Fuel Consumption City (L/100 km)         12.1      11.9      11.8      12.8   
Fuel Consumption Hwy (L/100 km)           8.7       7.7       8.1       9.0   
Fuel Consumption Comb (L/100 km)         10.6      10.0      10.1      11.1   
Fuel Consumption Comb (mpg)                27        28        28        25   
CO2 Emissions(g/km)                       244       230       232       255   

                                      8        9     ...        7375  \
Make                                 ACURA    ACURA  ...       VOLVO   
Model                               TL AWD      TSX  ...  S90 T6 AWD   
Vehicle Class                     MID-SIZE  COMPACT  ...    MID-SIZE   
Engine Size(L)                         3.7      2.4  ...         2.0   
Cylinders                                6        4  ...           4   
Transmission                            M6      AS5  ...         AS8   
Fuel Type                                Z        Z  ...           Z   
Fuel Consumption City (L/100 km)      13.4     10.6  ...        11.3   
Fuel Consumption Hwy (L/100 km)        9.5      7.5  ...         7.5   
Fuel Consumption Comb (L/100 km)      11.6      9.2  ...         9.6   
Fuel Consumption Comb (mpg)             24       31  ...          29   
CO2 Emissions(g/km)                    267      212  ...         223   

                                                   7376  \
Make                                              VOLVO   
Model                                            V60 T5   
Vehicle Class                     STATION WAGON - SMALL   
Engine Size(L)                                      2.0   
Cylinders                                             4   
Transmission                                        AS8   
Fuel Type                                             Z   
Fuel Consumption City (L/100 km)                   10.5   
Fuel Consumption Hwy (L/100 km)                     7.1   
Fuel Consumption Comb (L/100 km)                    8.9   
Fuel Consumption Comb (mpg)                          32   
CO2 Emissions(g/km)                                 208   

                                                   7377  \
Make                                              VOLVO   
Model                                        V60 T6 AWD   
Vehicle Class                     STATION WAGON - SMALL   
Engine Size(L)                          

In [4]:
new_df=data[['Engine Size(L)','Cylinders','Fuel Consumption Comb (L/100 km)','CO2 Emissions(g/km)']]
print(new_df.head())

   Engine Size(L)  Cylinders  Fuel Consumption Comb (L/100 km)  \
0             2.0          4                               8.5   
1             2.4          4                               9.6   
2             1.5          4                               5.9   
3             3.5          6                              11.1   
4             3.5          6                              10.6   

   CO2 Emissions(g/km)  
0                  196  
1                  221  
2                  136  
3                  255  
4                  244  


In [5]:
X=new_df.iloc[:,:3].values
y=new_df.iloc[:,-1:].values
print(y)

[[196]
 [221]
 [136]
 ...
 [240]
 [232]
 [248]]


In [6]:
import numpy as np
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit(X[:,:3])
X[:,:3]=imp.transform(X[:,:3])  # import numpy as np

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor(n_estimators=100, random_state=42)
reg.fit(X_train,y_train)
reg.score(X_train,y_train)
import joblib
joblib.dump(reg, 'vemodel.pkl')

c:\Users\gnoel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


['vemodel.pkl']

In [9]:
y_pred=reg.predict(X_test)
print(y_pred)
print(X_test)

[239.04111441 198.89715175 255.15849803 ... 242.12674026 139.51438889
 227.88685702]
[[ 3.   6.  10.3]
 [ 2.   4.   8.5]
 [ 3.8  6.  11. ]
 ...
 [ 2.5  4.  10.4]
 [ 2.5  4.   6. ]
 [ 2.5  4.   9.8]]


In [10]:
from sklearn.metrics import r2_score
Accuracy=r2_score(y_test,y_pred)*100
print(" Accuracy of the model-R2 is %.2f" %Accuracy)

 Accuracy of the model-R2 is 97.23


In [11]:
new_data = np.array([[2.0,4.0,8.5]])

In [12]:
new_prediction =reg.predict(new_data)

In [13]:
print(f"Prediction for new data: {new_prediction}")

Prediction for new data: [198.89715175]
